name: CI + CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!

stages:
  - Build
  - Deploy

DeployDev:
  name: Deploy to Dev
  if: github.event_name == 'pull_request'
  runs-on: ubuntu-latest
  needs: Build
  environment:
    name: Development
    url: 'http://dev.myapp.com'
  steps:
    - name: Deploy
      run: echo I am deploying to Dev!

DeployStaging:
  name: Deploy to Staging
  if: github.event.ref == 'refs/heads/main'
  runs-on: ubuntu-latest
  needs: Build
  environment:
    name: Staging
    url: 'http://test.myapp.com'
  steps:
    - name: Deploy
      run: echo I am deploying to Staging!

DeployProd:
  name: Deploy to Production
  runs-on: ubuntu-latest
  needs: Build
  environment:
    name: Production
    url: 'http://www.myapp.com'
  steps:
    - name: Deploy
      run: echo I am deploying to Production!
